[project]
name = "personal-knowledge-management-with-self-hosted-llm"
version = "0.1.0"
description = "TODO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"accelerate>=1.11.0",
	"chromadb>=1.2.1",
    "datasets>=2.14.0",
	"jupyter>=1.1.1",
	"sentence-transformers>=5.1.2",
    "torch>=2.0.0",
	"transformers>=4.57.1",
]
